"use strict";
// const num = 5;
// const myName = "Fazley";
// console.log(`${myName}`, num);
// let money = 5000;
// money = 12;
// let honey = "";
// let coni = false;
let money = 12;
let myName = "Fazley";
